-- 1 --
CREATE TABLE EWIDENCJACZASUPRACY(
IDEWIDENCJA INT PRIMARY KEY,
IDPRACOWNIKA INT,
OKRES VARCHAR2(30),
CZASPRACY INT
);

-- 2 --
CREATE TABLE FIRMA(
	ID INT PRIMARY KEY, 
	NAZWAFIRMY VARCHAR2(255), 
	SKROTFIRMY VARCHAR2(100), 
	MIEJSCOWOSC VARCHAR2(100), 
	ULICA VARCHAR2(100), 
	NRDOMU VARCHAR2(30), 
	NRLOKALU VARCHAR2(30), 
	WOJEWODZTWO VARCHAR2(30), 
	POWIAT VARCHAR2(50), 
	GMINA VARCHAR2(100), 
	KODTERYT INT, 
	KODPOCZTOWY VARCHAR2(6), 
	POCZTA VARCHAR2(100), 
	NIP INT, 
	REGON INT, 
	URZADSKARBOWY INT, 
	KONTOUS VARCHAR2(40), 
	KONTOZUS VARCHAR2(40), 
	STATUSPRAWNY INT
);

-- 3 --
CREATE TABLE ODDZIALYNFZ(
	IDNFZ INT PRIMARY KEY,
	KODODDZIALUNFZ VARCHAR2(150) NOT NULL,
	NAZWAODDZIALUNFZ VARCHAR2(150) NOT NULL
);

-- 4 --
CREATE TABLE PLEC(
	IDPLEC INT PRIMARY KEY,
	PLEC VARCHAR2(30) NOT NULL
);

-- 5 --
CREATE TABLE PRACOWNICY(
	IDPRACOWNIKA INT PRIMARY KEY, 
	IDFIRMY INT NOT NULL, 
	NRAKT INT, 
	NAZWISKO VARCHAR2(100), 
	IMIE VARCHAR2(100), 
	IMIE2 VARCHAR2(100), 
	PLEC INT NOT NULL, 
	DATAURODZENIA DATE, 
	MIEJSCEURODZENIA VARCHAR2(100), 
	IMIEOJCA VARCHAR2(100), 
	IMIEMATKI VARCHAR2(100), 
	NAZWISKORODOWE VARCHAR2(100), 
	NAZWISKORODOWEMATKI VARCHAR2(100), 
	PESEL VARCHAR2(11), 
	NIP INT, 
	STANCYWILNY INT, 
	KODPOCZTOWY VARCHAR2(6), 
	POCZTA VARCHAR2(100), 
	MIEJSCOWOSC VARCHAR2(100), 
	ULICA VARCHAR2(100), 
	NRBUDYNKU VARCHAR2(20), 
	Z_KODPOCZTOWY VARCHAR2(6), 
	Z_POCZTA VARCHAR2(100), 
	Z_MIEJSCOWOSC VARCHAR2(100), 
	Z_ULICA VARCHAR2(100), 
	Z_NRBUDYNKU VARCHAR2(20), 
	KODODDZIALYNFZ INT NOT NULL, 
	TELEFON VARCHAR2(100), 
	EMAIL VARCHAR2(100), 
	OBYWATELSTWO INT, 
	OPIS VARCHAR2(200), 
	WOJEWODZTWO VARCHAR2(30), 
	POWIAT VARCHAR2(50), 
	GMINA VARCHAR2(100)
);

-- 6 --
CREATE TABLE PRACOWNICYZUS(
	IDZUS INT PRIMARY KEY, 
	IDPRACOWNIKA INT NOT NULL, 
	KODUBEZPIECZENIA INT, 
	PRAWODOEMERYTURY INT, 
	STOPIENNIEPELNOSPRAWNOSCI INT, 
	DATAPOWSTANIAOBOWIAZKUSPOLECZNEGO DATE, 
	DATAZAKONCZENIAOBOWIAZKUSPOLECZNEGO DATE, 
	DATAPOWSTANIAOBOWIAZKUZDROWOTNEGO DATE, 
	DATAZAKONCZENIAOBOWIAZKUZDROWOTNEGO DATE, 
	EMERYTALNE INT, 
	RENTOWE INT, 
	CHOROBOWE INT, 
	WYPADKOWE INT
);

-- 7 --
CREATE TABLE TRANSAKCJE(
	IDTRANSAKCJI INT PRIMARY KEY, 
	IDWYNAGRODZENIA INT, 
	DATATRANSAKCJI DATE, 
	KWOTA INT, 
	DATAROZLICZENIA DATE, 
	SPOSOBPLATNOSCI VARCHAR2(40), 
	IDROZLICZENIA INT
);

-- 8 --
CREATE TABLE UMOWYPRACOWNICZE(
	IDUMOWY INT PRIMARY KEY, 
	IDPRACOWNIKA INT NOT NULL, 
	RODZAJUMOWY VARCHAR2(50) NOT NULL, 
	DATAUMOWY DATE NOT NULL, 
	OKRESUMOWYOD DATE NOT NULL, 
	OKRESUMOWYDO DATE, 
	STAWKA INT, 
	RODZAJSTAWKI VARCHAR2(50), 
	STANOWISKO VARCHAR2(100), 
	WIELKOSCETATU VARCHAR2(4)
);

-- 9 --
CREATE TABLE WOJEWODZTWA(
	IDWOJEWODZTWA INT PRIMARY KEY, 
	NAZWAWOJEWODZTWA VARCHAR2(50) NOT NULL, 
	POWIAT VARCHAR2(100), 
	GMINA VARCHAR2(100), 
	KODTERYT INT, 
	KODPOCZTOWY VARCHAR2(6), 
	POCZTA VARCHAR2(100)
);

-- 10 --
CREATE TABLE WYNAGRODZENIA(
	IDWYNAGRODZENIA INT PRIMARY KEY, 
	IDPRACOWNIKA INT NOT NULL, 
	OKRES VARCHAR2(30), 
	PLACAZASADNICZA INT, 
	WYNAGRODZENIACHOROBOWE INT, 
	ZASILEKCHOROBOWY INT, 
	WYNAGRODZENIEURLOPOWE INT
);