-- USUWANIE TABEL --
DROP TABLE EWIDENCJACZASUPRACY CASCADE CONSTRAINTS PURGE;
DROP TABLE FIRMA CASCADE CONSTRAINTS PURGE;
DROP TABLE ODDZIALYNFZ CASCADE CONSTRAINTS PURGE;
DROP TABLE PLEC CASCADE CONSTRAINTS PURGE;
DROP TABLE PRACOWNICY CASCADE CONSTRAINTS PURGE;
DROP TABLE PRACOWNICYZUS CASCADE CONSTRAINTS PURGE;
DROP TABLE TRANSAKCJE CASCADE CONSTRAINTS PURGE;
DROP TABLE UMOWYPRACOWNICZE CASCADE CONSTRAINTS PURGE;
DROP TABLE WOJEWODZTWA CASCADE CONSTRAINTS PURGE;
DROP TABLE WYNAGRODZENIA CASCADE CONSTRAINTS PURGE;